services:
  web:
    image: traaaashpanda/furrymusicdb:latest
    build:
      context: .
      target: development
    depends_on:
      - db
    volumes:
      - .:/var/app/www
      - uploads:/var/app/uploads
    env_file: dev.env
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    logging: &default-logging
      options:
        max-size: "1m"
        max-file: "5"

  db:
    image: docker.io/library/postgres:16-alpine
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    env_file: dev.env
    ports:
      - "127.0.0.1:5432:5432"
    logging: *default-logging

volumes:
  uploads: { }
  pgsql_data: { }
